dashboard_admin:
    locales:
        en: "/dashboard"
        fr: "/tableau-de-bord"
    defaults: { _controller: AdminBundle:Admin:index }

list_proposer_admin:
    locales:
        en: "/proposer/list"
        fr: "/proposeur/liste"
    defaults: { _controller: AdminBundle:Admin:listProposer }

list_voter_admin:
    locales:
        en: "/voter/list"
        fr: "/voteur/liste"
    defaults: { _controller: AdminBundle:Admin:listVoter }

list_admin:
    locales:
        en: "/admin/list"
        fr: "/admin/liste"
    defaults: { _controller: AdminBundle:Admin:listAdmin }

remove_admin:
    locales:
        en: "/remove-admin"
        fr: "/supprimer-admin"
    defaults: { _controller: AdminBundle:Admin:removeFromAdmin }

promote_admin:
    locales:
        en: "/promote-to--admin"
        fr: "/ajouter-admin"
    defaults: { _controller: AdminBundle:Admin:promoteToAdmin }

list_offer_admin:
    locales:
        en: "/offer/list"
        fr: "/offre/liste"
    defaults: { _controller: AdminBundle:Admin:listOffer }

change_validation_status:
    locales:
        en: "/change-validation-status"
        fr: "/changer-status-validation"
    defaults: { _controller: AdminBundle:Admin:changeValidationStatus }

close_estimation:
    locales:
        en: "/close-estimation"
        fr: "/fermer-estimation"
    defaults: { _controller: AdminBundle:Admin:closeEstimation }

change_estimation:
    locales:
        en: "/change-estimation"
        fr: "/changer-estimation"
    defaults: { _controller: AdminBundle:Admin:changeEstimation }

send_interested_mail:
    locales:
        en: "/send-interested-mail"
        fr: "/envoyer-mail-interesses"
    defaults: { _controller: AdminBundle:Admin:sendInterestedMail }

vote_page:
    locales:
        en: "/vote-page"
        fr: "/page-vote"
    defaults: { _controller: AdminBundle:Admin:listVotePage }
log_page:
    locales:
        en: "/log-page"
        fr: "/page-stat"
    defaults: { _controller: AdminBundle:Admin:logPage }

list_ad_admin:
    locales:
        en: "/ad/list/{archived}"
        fr: "/pub/liste/{archived}"
    defaults: { _controller: AdminBundle:Ad:listAd }

create_ad:
    locales:
        en: "/ad/create"
        fr: "/pub/creation"
    defaults: { _controller: AdminBundle:Ad:create }

edit_ad:
    locales:
        en: "/ad/edit"
        fr: "/pub/edition"
    defaults: { _controller: AdminBundle:Ad:edit }
archive_ad:
    locales:
        en: "/ad/archive"
        fr: "/pub/archiver"
    defaults: { _controller: AdminBundle:Ad:archive }