dashboard_admin:
    locales:
        en: "/dashboard"
        fr: "/tableau-de-bord"
    defaults: { _controller: AdminBundle:Admin:index }

list_employer_admin:
    locales:
        en: "/employer/list"
        fr: "/employeur/liste"
    defaults: { _controller: AdminBundle:Admin:listEmployer }