<?php

namespace AppBundle\Repository;

/**
 * VoterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoterRepository extends \Doctrine\ORM\EntityRepository
{

    public function countActiveBetween($endDate){
        return $this->getEntityManager()
            ->createQuery(
                'select count(distinct ca.id) as total
                    from AppBundle:voter ca
                    where ca.creationDate <= :endDate'
            )->setParameter('endDate',$endDate)->execute();
    }

}
