employer:
    resource: "@EmployerBundle/Controller/"
    type:     annotation
    prefix:   /employer

app:
    resource: '@AppBundle/Resources/config/routing.yml/'
    prefix:   /{_locale}/
    requirements:
      _locale: fr|en


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}/