root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/
        permanent: true

proposer:
    resource: "@ProposerBundle/Resources/config/routing.yml"
    type: "be_simple_i18n"
    prefix:
         en: "/{_locale}/proposer"
         fr: "/{_locale}/proposeur"

voter:
    resource: "@VoterBundle/Resources/config/routing.yml"
    type: "be_simple_i18n"
    prefix:
        en: "/{_locale}/voteur"
        fr: "/{_locale}/voter"

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    type: "be_simple_i18n"
    prefix:
        en: "/{_locale}/admin"
        fr: "/{_locale}/admin"

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    type: "be_simple_i18n"
    prefix:
        en: "/{_locale}/"
        fr: "/{_locale}/"
    requirements:
      _locale: fr|en

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}/

fos_user_resetting_request:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:
        en: "/forgot-password"
        fr: "/mot-de-passe-oublie"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:
        en: "/change-password"
        fr: "/changer-mot-de-passe"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /