create_proposer:
    locales:
        en: "/register"
        fr: "/inscription"
    defaults: { _controller: ProposerBundle:Proposer:create }
edit_proposer:
    locales:
        en: "/edit"
        fr: "/editer"
    defaults: { _controller: ProposerBundle:Proposer:edit }
delete_proposer:
    locales:
        en: "/delete/{id}"
        fr: "/supprimer/{id}"
    defaults: { _controller: ProposerBundle:Proposer:delete }

show_proposer:
    locales:
        en: "/{id}"
        fr: "/{id}"
    defaults: { _controller: ProposerBundle:Proposer:show }
    requirements:
        id: \d+
list_proposer:
    locales:
        en: "/list-proposer"
        fr: "/liste-employeur"
    defaults: { _controller: ProposerBundle:Proposer:list }
dashboard_proposer:
    locales:
        en: "/dashboard"
        fr: "/tableaux-de-bord"
    defaults: { _controller: ProposerBundle:Proposer:dashboard}
proposer_offers:
    locales:
        en: "/my-offers/{archived}"
        fr: "/mes-offres/{archived}"
    defaults: { _controller: ProposerBundle:Proposer:myOfferPage , archived: 0}
    requirements:
      archived: 0|1
post_offer:
    locales:
        en: "/post-offer"
        fr: "/creation-offre"
    defaults: { _controller: ProposerBundle:Offer:post }
edit_offer:
    locales:
        en: "/edit-offer/{id}"
        fr: "/edition-offre/{id}"
    defaults: { _controller: ProposerBundle:Offer:edit }
    requirements:
      id: \d+
delete_offer:
    locales:
        en: "/delete-offer"
        fr: "/supprimer-offre"
    defaults: { _controller: ProposerBundle:Offer:delete }
    requirements:
      id: \d+
erase_offer:
    locales:
        en: "/erase-offer"
        fr: "/effacer-offre"
    defaults: { _controller: ProposerBundle:Offer:erase }
    requirements:
      id: \d+
show_offer:
    locales:
        en: "/offer/{url}/{id}"
        fr: "/offre/{url}/{id}"
    defaults: { _controller: ProposerBundle:Offer:show }
    requirements:
        url:    .*
vote_offer:
    locales:
        en: "/vote/{id}"
        fr: "/voter/{id}"
    defaults: { _controller: ProposerBundle:Offer:vote }
    requirements:
      id: \d+
search_offer:
    locales:
        en: "/search-offer"
        fr: "/chercher-offre"
    defaults: { _controller: ProposerBundle:Offer:search }
search_page_offer:
    locales:
        en: "/search-offer-page"
        fr: "/page-chercher-offre"
    defaults: { _controller: ProposerBundle:Offer:searchPage }
boost_offers:
    locales:
        en: "/boost-offer"
        fr: "/booster-offre"
    defaults: { _controller: ProposerBundle:Offer:boost }
delete_image:
    locales:
        en: "/delete-image"
        fr: "/effacer-image"
    defaults: { _controller: ProposerBundle:Offer:deleteImage }
increment_offer:
    locales:
        en: "/increment-offer"
        fr: "/incrementer-offre"
    defaults: { _controller: ProposerBundle:Offer:increment }
featured_proposer_page:
    locales:
        en: "/featured-proposer"
        fr: "/employeur-en-avant"
    defaults: { _controller: ProposerBundle:Proposer:featuredProposerPage }
reserve_featured_proposer:
    locales:
        en: "/reserve-featured-proposer"
        fr: "/reserver-employeur-en-avant"
    defaults: { _controller: ProposerBundle:Proposer:reserveFeaturedProposer }
delete_featured_proposer:
    locales:
        en: "/delete-featured-proposer"
        fr: "/supprimer-employeur-en-avant"
    defaults: { _controller: ProposerBundle:Proposer:deleteFeaturedProposer }
featured_offer_page:
    locales:
        en: "/featured-offer"
        fr: "/offre-en-avant"
    defaults: { _controller: ProposerBundle:Proposer:featuredOfferPage }
reserve_featured_offer:
    locales:
        en: "/reserve-featured-offer"
        fr: "/reserver-offre-en-avant"
    defaults: { _controller: ProposerBundle:Proposer:reserveFeaturedOffer }
delete_featured_offer:
    locales:
        en: "/delete-featured-offer"
        fr: "/supprimer-offre-en-avant"
    defaults: { _controller: ProposerBundle:Proposer:deleteFeaturedOffer }
buy_slot:
    locales:
        en: "/buy-slot"
        fr: "/acheter-slot"
    defaults: { _controller: ProposerBundle:Proposer:buySlot }
add_to_slot:
    locales:
        en: "/add-to-slot"
        fr: "/ajouter-aux-slot"
    defaults: { _controller: ProposerBundle:Proposer:addToSlot }
    requirements:
      id: \d+
remove_from_slot:
    locales:
        en: "/remove-from-slot/{id}"
        fr: "/enlever-du-slot/{id}"
    defaults: { _controller: ProposerBundle:Proposer:removeFromSlot }
    requirements:
      id: \d+
empty_slot:
    locales:
        en: "/empty-slot/{id}"
        fr: "/vider-slot/{id}"
    defaults: { _controller: ProposerBundle:Proposer:EmptySlot }
    requirements:
      id: \d+
offer_archived:
    locales:
        en: "/offer-archived/{id}"
        fr: "/offre-archivé/{id}"
    defaults: { _controller: ProposerBundle:Offer:offerNotFound }
applied_voter_page:
    locales:
        en: "/voters-for-offer/{id}"
        fr: "/candidats-a-offre/{id}"
    defaults: { _controller: ProposerBundle:Proposer:listAppliedVoterPage }
apply_spontaneous:
    locales:
        en: "/spontaneous-application/{id}"
        fr: "/candidature-spontane/{id}"
    defaults: { _controller: ProposerBundle:Proposer:sendSearch }
end_activation_offer_mail:
    locales:
        en: "/mail-end-activation"
        fr: "/mail-fin-activation"
    defaults: { _controller: ProposerBundle:Offer:sendEndActivation }
