jobnow_home:
    path:     /
    defaults: { _controller: AppBundle:App:index }
jobnow_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Contact:contact }
jobnow_credit:
    path:     /employer/credit
    defaults: { _controller: AppBundle:Credit:credit }

jobnow_payement:
    path:     /employer/payment/{id}
    defaults: { _controller: AppBundle:Credit:credit }
