create_candidate:
    locales:
        en: "/register"
        fr: "/inscription"
    defaults: { _controller: CandidateBundle:Candidate:create }
edit_candidate:
    locales:
        en: "/edit"
        fr: "/editer"
    defaults: { _controller: CandidateBundle:Candidate:edit }
delete_candidate:
    locales:
        en: "/delete"
        fr: "/supprimer"
    defaults: { _controller: CandidateBundle:Candidate:delete }
show_candidate:
    locales:
        en: "/{id}"
        fr: "/{id}"
    requirements:
      id: \d+
    defaults: { _controller: CandidateBundle:Candidate:show }
dashboard_candidate:
    locales:
        en: "/dashboard"
        fr: "/tableau-de-bord"
    defaults: { _controller: CandidateBundle:Candidate:dashboard }
search_candidate:
    locales:
        en: "/search"
        fr: "/chercher"
    defaults: { _controller: CandidateBundle:Candidate:search }