create_employer:
    path:     /register
    defaults: { _controller: EmployerBundle:Employer:create }
edit_employer:
    path:     /edit
    defaults: { _controller: EmployerBundle:Employer:edit }
delete_employer:
    path:     /delete/{id}
    defaults: { _controller: EmployerBundle:Employer:delete }

show_employer:
    path:     /{id}
    defaults: { _controller: EmployerBundle:Employer:show }
    requirements:
        id: \d+

dashboard_employer:
    path:     /dashboard/{archived}
    defaults: { _controller: EmployerBundle:Employer:dashboard , archived: 0}
    requirements:
      archived: 0|1
post_offer:
    path:     /post-offer
    defaults: { _controller: EmployerBundle:Offer:post }
edit_offer:
    path:     /edit-offer/{id}
    defaults: { _controller: EmployerBundle:Offer:edit }
    requirements:
      id: \d+
delete_offer:
    path:     /delete-offer/{id}
    defaults: { _controller: EmployerBundle:Offer:delete }
    requirements:
      id: \d+
activate_offer:
    path:     /activate-offer/{id}
    defaults: { _controller: EmployerBundle:Offer:activate }
    requirements:
      id: \d+
show_offer:
    path:     /show-offer/{id}
    defaults: { _controller: EmployerBundle:Offer:show }
    requirements:
      id: \d+