create_employer:
    path:     /register
    defaults: { _controller: EmployerBundle:Employer:create }
edit_employer:
    path:     /edit
    defaults: { _controller: EmployerBundle:Employer:edit }
delete_employer:
    path:     /delete/{id}
    defaults: { _controller: EmployerBundle:Employer:delete }

show_employer:
    path:     /{id}
    defaults: { _controller: EmployerBundle:Employer:show }
    requirements:
        id: \d+
list_employer:
    path:     /list-employer
    defaults: { _controller: EmployerBundle:Employer:list }
dashboard_employer:
    path:     /dashboard/{archived}
    defaults: { _controller: EmployerBundle:Employer:dashboard , archived: 0}
    requirements:
      archived: 0|1
post_offer:
    path:     /post-offer
    defaults: { _controller: EmployerBundle:Offer:post }
edit_offer:
    path:     /edit-offer/{id}
    defaults: { _controller: EmployerBundle:Offer:edit }
    requirements:
      id: \d+
delete_offer:
    path:     /delete-offer/{id}
    defaults: { _controller: EmployerBundle:Offer:delete }
    requirements:
      id: \d+
activate_offer:
    path:     /activate-offer/{id}
    defaults: { _controller: EmployerBundle:Offer:activate }
    requirements:
      id: \d+
show_offer:
    path:     /show-offer/{id}
    defaults: { _controller: EmployerBundle:Offer:show }
    requirements:
      id: \d+
apply_offer:
    path:     /apply-offer/{id}
    defaults: { _controller: EmployerBundle:Offer:apply }
    requirements:
      id: \d+
search_offer:
    path:     /search-offer
    defaults: { _controller: EmployerBundle:Offer:search }
search_page_offer:
    path:     /search-page-offer
    defaults: { _controller: EmployerBundle:Offer:searchPage }
boost_offers:
    path:     /boost-offer
    defaults: { _controller: EmployerBundle:Offer:boost }
featured_employer_page:
    path:     /featured-employer
    defaults: { _controller: EmployerBundle:Employer:featuredEmployerPage }
reserve_featured_employer:
    path:     /reserve-featured-employer
    defaults: { _controller: EmployerBundle:Employer:reserveFeaturedEmployer }
delete_featured_employer:
    path:     /delete-featured-employer
    defaults: { _controller: EmployerBundle:Employer:deleteFeaturedEmployer }
featured_offer_page:
    path:     /featured-offer
    defaults: { _controller: EmployerBundle:Employer:featuredOfferPage }
reserve_featured_offer:
    path:     /reserve-featured-offer
    defaults: { _controller: EmployerBundle:Employer:reserveFeaturedOffer }
delete_featured_offer:
    path:     /delete-featured-offer
    defaults: { _controller: EmployerBundle:Employer:deleteFeaturedOffer }
buy_slot:
    path:     /buy-slot
    defaults: { _controller: EmployerBundle:Employer:buySlot }
add_to_slot:
    path:     /add-to-slot/{id}
    defaults: { _controller: EmployerBundle:Employer:addToSlot }
    requirements:
      id: \d+
remove_from_slot:
    path:     /remove-from-slot/{id}
    defaults: { _controller: EmployerBundle:Employer:removeFromSlot }
    requirements:
      id: \d+
empty_slot:
    path:     /empty-slot/{id}
    defaults: { _controller: EmployerBundle:Employer:EmptySlot }
    requirements:
      id: \d+