create_employer:
    path:     /register
    defaults: { _controller: EmployerBundle:Employer:create }
edit_employer:
    path:     /edit
    defaults: { _controller: EmployerBundle:Employer:edit }
delete_employer:
    path:     /delete/{id}
    defaults: { _controller: EmployerBundle:Employer:delete }
dashboard_employer:
    path:     /dashboard
    defaults: { _controller: EmployerBundle:Employer:dashboard }
post_offer:
    path:     /post-offer
    defaults: { _controller: EmployerBundle:Employer:postOffer }
edit_offer:
    path:     /edit-offer/{id}
    defaults: { _controller: EmployerBundle:Employer:editOffer }
    requirements:
      id: \d+
delete_offer:
    path:     /delete-offer/{id}
    defaults: { _controller: EmployerBundle:Employer:deleteOffer }
    requirements:
      id: \d+
activate_offer:
    path:     /activate-offer/{id}
    defaults: { _controller: EmployerBundle:Employer:activateOffer }
    requirements:
      id: \d+